# Generated by Django 3.2.6 on 2021-10-06 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Interaction', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='group',
        ),
        migrations.AddField(
            model_name='notification',
            name='reciever',
            field=models.ManyToManyField(related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
