# Generated by Django 3.2.6 on 2021-10-07 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Interaction', '0004_auto_20211006_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reciever',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='redirect_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
