# Generated by Django 3.2.6 on 2021-09-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Misc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
