# Generated by Django 3.2.6 on 2021-09-03 15:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Misc', '0002_remove_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(default='Hey'),
            preserve_default=False,
        ),
    ]
