# Generated by Django 3.2.6 on 2021-09-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misc', '0005_auto_20210904_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
