version : "3.9"

services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code 
    depends_on:
      - db  
      - redis 
      
  db:
    image: postgres:latest   
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aquazinc
    ports:
      - "5432:5432" 
    volumes:
      - clinic_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data  
    
volumes:
  clinic_data:
  redis_data:

  
