# Generated by Django 3.2.6 on 2021-09-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.ManyToManyField(to='Personnel.Specialization'),
        ),
    ]
